### ISSUE TITLE
fails to build with adplug-2.2.1

### ISSUE THREAD

**Issue by ildar** [adplug/adplay-unix#13]
> adplay.cc:28:10: fatal error: adplug/wemuopl.h: No such file or directory
>  #include <adplug/wemuopl.h>

this file doesn't yet exist in that old version.
This is a minor bug.

**Comment by Malvineous** [comment]
Which version are you compiling?  The latest git adplay-unix will always require the latest git adplug.
